ERROR: There are scenarios with duplicate names:
  foo

